void set_fields_Zalesak(Triangulation& T) ;
void set_vels_rotating(Triangulation& T) ;
void set_fields_TG(Triangulation& T) ;
void set_fields_cos(Triangulation& T) ;
void set_forces_Kolmo(Triangulation& T) ;
void set_forces_Kolmo(Triangulation& T, const int nn ) ;
void set_alpha_circle(Triangulation& T, const FT&) ;
void set_alpha_under_cos( Triangulation& T );
void set_alpha_cos( Triangulation& T );
void set_alpha_random( Triangulation& T ) ;
void zero_mean_v( Triangulation& T ,  const kind::f vectorf );
void set_vels_Gresho(Triangulation& T);
